"use client";

import { useActionState, useState } from "react";
import { useFormStatus } from "react-dom";
import { Button } from "@/components/ui/button";
import { initialQuizState, type QuizActionState } from "@/lib/validations/quiz";

type Action = (state: QuizActionState, formData: FormData) => Promise<QuizActionState>;
const input = "h-11 w-full rounded-xl border bg-background px-3 outline-none focus-visible:ring-2 focus-visible:ring-ring";
function Submit({ children }: { children: React.ReactNode }) { const { pending } = useFormStatus(); return <Button disabled={pending}>{pending ? "Saving…" : children}</Button>; }
function Message({ state }: { state: QuizActionState }) { return state.message ? <p role="alert" className="rounded-xl border border-destructive/30 bg-destructive/10 p-3 text-sm text-destructive">{state.message}</p> : null; }

type QuizDefaults = { title?: string; description?: string | null; subject?: string | null; difficulty?: string; game_mode?: string };
export function QuizForm({ action, defaults = {}, submitLabel }: { action: Action; defaults?: QuizDefaults; submitLabel: string }) {
  const [state, formAction] = useActionState(action, initialQuizState); const value = (key: string, fallback = "") => state.fields?.[key] ?? fallback;
  return <form action={formAction} className="space-y-5"><Message state={state} /><label className="block space-y-2"><span className="text-sm font-medium">Title</span><input className={input} name="title" required maxLength={150} defaultValue={value("title", defaults.title)} /></label><label className="block space-y-2"><span className="text-sm font-medium">Description <span className="text-muted-foreground">(optional)</span></span><textarea className="min-h-24 w-full rounded-xl border bg-background p-3 outline-none focus-visible:ring-2 focus-visible:ring-ring" name="description" maxLength={2000} defaultValue={value("description", defaults.description ?? "")} /></label><label className="block space-y-2"><span className="text-sm font-medium">Subject <span className="text-muted-foreground">(optional)</span></span><input className={input} name="subject" maxLength={100} defaultValue={value("subject", defaults.subject ?? "")} /></label><div className="grid gap-5 sm:grid-cols-2"><label className="block space-y-2"><span className="text-sm font-medium">Difficulty</span><select className={input} name="difficulty" defaultValue={value("difficulty", defaults.difficulty ?? "medium")}><option value="easy">Easy</option><option value="medium">Medium</option><option value="hard">Hard</option></select></label><label className="block space-y-2"><span className="text-sm font-medium">Game mode</span><select className={input} name="gameMode" defaultValue={value("gameMode", defaults.game_mode ?? "classic")}><option value="classic">Classic</option><option value="time_attack">Time Attack</option><option value="survival">Survival</option></select></label></div><Submit>{submitLabel}</Submit></form>;
}

type QuestionDefaults = { question_text?: string; question_type?: "multiple_choice" | "true_false"; choices?: unknown; correct_answer?: string; points?: number };
export function QuestionForm({ action, defaults = {}, submitLabel }: { action: Action; defaults?: QuestionDefaults; submitLabel: string }) {
  const [state, formAction] = useActionState(action, initialQuizState); const [type, setType] = useState(state.fields?.questionType ?? defaults.question_type ?? "multiple_choice");
  const choices = Array.isArray(defaults.choices) ? defaults.choices.filter((item): item is string => typeof item === "string") : [];
  const value = (key: string, fallback = "") => state.fields?.[key] ?? fallback;
  return <form action={formAction} className="space-y-4"><Message state={state} /><label className="block space-y-2"><span className="text-sm font-medium">Question</span><textarea className="min-h-24 w-full rounded-xl border bg-background p-3 outline-none focus-visible:ring-2 focus-visible:ring-ring" name="questionText" required maxLength={2000} defaultValue={value("questionText", defaults.question_text)} /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block space-y-2"><span className="text-sm font-medium">Type</span><select className={input} name="questionType" value={type} onChange={(event) => setType(event.target.value)}><option value="multiple_choice">Multiple choice</option><option value="true_false">True / False</option></select></label><label className="block space-y-2"><span className="text-sm font-medium">Points</span><input className={input} name="points" type="number" min={1} max={100} defaultValue={value("points", String(defaults.points ?? 10))} required /></label></div>{type === "multiple_choice" ? <><div className="grid gap-3 sm:grid-cols-2">{[0,1,2,3].map((index) => <label key={index} className="block space-y-2"><span className="text-sm font-medium">Choice {index + 1}{index > 1 && " (optional)"}</span><input className={input} name={`choice${index + 1}`} required={index < 2} defaultValue={value(`choice${index + 1}`, choices[index])} /></label>)}</div><label className="block space-y-2"><span className="text-sm font-medium">Correct answer</span><input className={input} name="correctAnswer" required defaultValue={value("correctAnswer", defaults.correct_answer)} placeholder="Must exactly match a choice" /></label></> : <label className="block space-y-2"><span className="text-sm font-medium">Correct answer</span><select className={input} name="correctAnswer" defaultValue={value("correctAnswer", defaults.correct_answer ?? "true")}><option value="true">True</option><option value="false">False</option></select></label>}<Submit>{submitLabel}</Submit></form>;
}

export function AssignmentForm({ action, classes }: { action: Action; classes: { id: string; name: string }[] }) {
  const [state, formAction] = useActionState(action, initialQuizState);
  return <form action={formAction} className="space-y-4"><Message state={state} /><label className="block space-y-2"><span className="text-sm font-medium">Class</span><select className={input} name="classId" required defaultValue={state.fields?.classId ?? ""}><option value="" disabled>Select a class</option>{classes.map((item) => <option key={item.id} value={item.id}>{item.name}</option>)}</select></label><label className="block space-y-2"><span className="text-sm font-medium">Due date <span className="text-muted-foreground">(optional)</span></span><input className={input} name="dueAt" type="datetime-local" defaultValue={state.fields?.dueAt} /></label><Submit>Assign quiz</Submit></form>;
}
